export const contentIcons = [
  { title: "Calendar", value: "calendar" },
  { title: "Camera", value: "camera" },
  { title: "Check", value: "check-circle" },
  { title: "Clock", value: "clock" },
  { title: "Cocktail", value: "cocktail" },
  { title: "Coins", value: "coins" },
  { title: "Cube", value: "cube" },
  { title: "Die (one)", value: "die-1" },
  { title: "Die (two)", value: "die-2" },
  { title: "Disc", value: "disc" },
  { title: "Hourglass", value: "hourglass" },
  { title: "House", value: "house" },
  { title: "Lock", value: "lock" },
  { title: "Mail", value: "mail" },
  { title: "Medal", value: "medal" },
  { title: "Music note", value: "music-note" },
  { title: "Phone", value: "phone" },
  { title: "Pin", value: "pin" },
  { title: "Question", value: "question" },
  { title: "Rosette", value: "rosette" },
  { title: "Sparkles", value: "sparkles" },
  { title: "Star", value: "star" },
  { title: "User", value: "user" },
  { title: "Two people", value: "users-2" },
  { title: "Three people", value: "users-3" },
  { title: "Four people", value: "users-4" },
];
